#!/bin/bash
clear
lineas="===================================="
red='\033[1;31m'                                        
green='\033[1;32m'
yellow='\033[1;33m'                                   
blue='\033[1;34m'                                       
magenta='\033[1;35m'                                    
cyan='\033[1;36m'
reset='\033[0m'
printf $red
v=3.0
echo $lineas

echo "╻ ╻┏━┓╻ ╻╺┳┓┏━┓╻ ╻┏┓╻╻  ┏━┓┏━┓╺┳┓
┗┳┛┃ ┃┃ ┃ ┃┃┃ ┃┃╻┃┃┗┫┃  ┃ ┃┣━┫ ┃┃
 ╹ ┗━┛┗━┛╺┻┛┗━┛┗┻┛╹ ╹┗━╸┗━┛╹ ╹╺┻┛
"
echo $v
echo $lineas

printf $green
read -p "Que descargaras :
 [1] Música 
 [2] Video 
 [3] Salir " arch
printf $reset

case $arch in
		[Cc]ancion|Canción|canción|1)

printf $red
read -p "Que quieres descargar:
	[1] Canción 
	[2] Playlist 
	[3] Salir " arch
case $arch in
	[Cc]ancion|Canción|canción|1)
		echo $lineas
		read -p "Pega la URL de la canción _>" Ind
		if [ -z $Ind ];then
			echo $lineas
			echo "No ingresante una url _>"
			exit
		fi
		
		sleep 0.5
		echo "Iniciando descarga _>"
		yt-dlp -f bestaudio --embed-thumbnail --extract-audio --audio-format mp3 --audio-quality 0 $Ind
		sleep 0.5 
		echo $lineas
		echo "Descarga finalizada, el archivo se encuentra en: _>"
		pwd
		;;
	[Pp]laylist|2)
		read -p "Pega la URL de la playlist _>" Play
		if [ -z $Play ];then
			echo "No ingresante una url _>"
			exit
		fi
		echo $lineas
		sleep 0.5
		echo "Preparando descarga _>"
		yt-dlp --ignore-errors --format bestaudio --extract-audio --audio-format mp3 --audio-quality 160K --output "%(title)s.%(ext)s" --yes-playlist $Play
		echo $lineas
		;;
	 [3]|*)
		echo $lineas
		echo "<_Adiós_>"
		echo $lineas
esac

	printf $reset

		
		;;
		Vv]ideo|2)
printf $cyan
read -p "Que quieres descargar:
 	[1] Vídeo
 	[2] Playlist 
 	[3] Salir " pregunta

case $pregunta in
	[Vv]ideo|1)
	 echo $lineas

		read -p "Pega la URL del vídeo _> " vi
		if [ -z $vi ];then
			echo $lineas
			echo "No ingresaste una url valida _>"
			exit
		fi
		
		sleep 0.5
		echo "Iniciando descarga _> "
		yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 $vi
		sleep 0.5
		echo $lineas
		echo "Descarga finalizada, el archivo se encuentra en: _>"
		pwd
	;;
	[Pp]laylist|2)
		read -p "Pega la URL de la playlist " Play
		if [ -z $Play ];then
			echo "No ingresante una url valida _>"
			exit
		fi
		echo $lineas
		sleep 0.5
		echo "Preparando descarga _>"
		yt-dlp -f 'bestvideo[height<=1080]+bestaudio/best[height<=1080]' $Play
		echo $lineas
	;;
	 [3]|*)
		echo $lineas
		echo "<_Adiós_>"
		echo $lineas
esac
		
		;;
	 [3]|*)
		echo $lineas
		echo "<_Adiós_>"
		echo $lineas
esac
		
			
